# Generated by Django 6.0.6 on 2026-06-21 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='images',
            new_name='property_image',
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='airbnb_app.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_properties', to='airbnb_app.city'),
        ),
        migrations.AlterField(
            model_name='review',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_reviews', to='airbnb_app.property'),
        ),
    ]
