# Generated by Django 6.0.6 on 2026-06-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0002_rename_images_property_property_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_per_night',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
