# Generated by Django 6.0.6 on 2026-06-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0003_property_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='name_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ky',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='address_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='address_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='address_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_name_en',
            field=models.CharField(max_length=62, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_name_ky',
            field=models.CharField(max_length=62, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_name_ru',
            field=models.CharField(max_length=62, null=True),
        ),
    ]
