# Generated by Django 6.0.6 on 2026-06-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0005_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='product',
            new_name='property',
        ),
    ]
